blank_issues_enabled: false
contact_links:
  - name: Questions and general discussion
    url: https://github.com/asciifaceman/jave/discussions
    about: Please use Discussions for Q&A and open-ended conversation.
